# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_USE_QTOPENGL TRUE)
INCLUDE(${QT_USE_FILE})

IF(WIN32)
    IF($ENV{ProgramW6432})
        SET(EXPERIMENTAL_THEATRE_INSTALL_PREFIX $ENV{ProgramW6432}/ExperimentalTheatre)
    ELSE($ENV{ProgramW6432})
        SET(EXPERIMENTAL_THEATRE_INSTALL_PREFIX $ENV{ProgramW6432}/ExperimentalTheatre)
    ENDIF($ENV{ProgramW6432})
    LINK_DIRECTORIES(${EXPERIMENTAL_THEATRE_INSTALL_PREFIX}/lib)
ELSE(WIN32)
    SET(EXPERIMENTAL_THEATRE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
ENDIF(WIN32)
    
SET(MOUVEMENT_DE_MASSE_INCLUDE_DIRS
    ${MOUVEMENT_DE_MASSE_SRC_DIR}
    ${EXPERIMENTAL_THEATRE_INSTALL_PREFIX}/include/CellarWorkbench
    ${EXPERIMENTAL_THEATRE_INSTALL_PREFIX}/include/MediaWorkbench
    ${EXPERIMENTAL_THEATRE_INSTALL_PREFIX}/include/PropRoom2D
    ${EXPERIMENTAL_THEATRE_INSTALL_PREFIX}/include/Scaena)

SET(MOUVEMENT_DE_MASSE_LIBRARIES
    ${QT_LIBRARIES}
    CellarWorkbench
    MediaWorkbench
    PropRoom2D
    Scaena
)
