# Qt
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_USE_QTOPENGL TRUE)
INCLUDE(${QT_USE_FILE})

SET(MOUVEMENT_DE_MASSE_LIBRARIES
    GLEW
    ${QT_LIBRARIES}
    CellarWorkbench
    PropRoom2D
    Scaena
)
    
SET(MOUVEMENT_DE_MASSE_INCLUDE_DIRS
    ${MOUVEMENT_DE_MASSE_SRC_DIR}
    ${MOUVEMENT_DE_MASSE_INSTALL_PREFIX}/include/CellarWorkbench
    ${MOUVEMENT_DE_MASSE_INSTALL_PREFIX}/include/PropRoom2D
    ${MOUVEMENT_DE_MASSE_INSTALL_PREFIX}/include/Scaena)
