# Qt
FIND_PACKAGE(Qt5OpenGL REQUIRED)
SET(CMAKE_AUTOMOC ON)

#Exth
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${MOUVEMENT_DE_MASSE_SRC_DIR}/../ExperimentalTheatre/")
FIND_PACKAGE(ExperimentalTheatre REQUIRED)


# Globals
SET(MOUVEMENT_DE_MASSE_LIBRARIES
    ${ExTh_LIBRARIES})
SET(MOUVEMENT_DE_MASSE_INCLUDE_DIRS
    ${MOUVEMENT_DE_MASSE_INCLUDE_DIRS}
    ${MOUVEMENT_DE_MASSE_SRC_DIR}
    ${ExTh_INCLUDE_DIRS})
SET(MOUVEMENT_DE_MASSE_QT_MODULES
    OpenGL)
